### ISSUE TITLE
Embed video not working for Youtube url

### ISSUE THREAD

**Issue by SanthoshVasabhaktula** [arvigeus/bootstrap3-wysihtml5#2]
Hi,

Tried to embed a youtube video with URL - https://www.youtube.com/watch?v=TBWX97e1E9g, but the resultant src on in the iframe is "//www.youtube.com/embed/https://www.youtube.com/watch?v=TBWX97e1E9g". Can you fix the parsing error?

**Comment by mrudult** [comment]
@SanthoshVasabhaktula @arvigeus 

I made a small patch for this.
Changed **line no 494 and 495** of [bootstrap3-wysihtml5.js](https://github.com/arvigeus/bootstrap3-wysihtml5/blob/master/dist/bootstrap3-wysihtml5.js#L494) to:
```
if (/^(https?\:\/\/(www\.)?(m\.)?youtube.com\/)/i.test(linkUrl)) {
                    //embedUrl = linkUrl.replace(/^(https?\:\/\/(www\.)?(m\.)?youtube.com\/)(watch?v=|v\/|embeded\/)/, "");
                    var video_id = linkUrl.split('v=')[1];
                    var ampersandPosition = video_id.indexOf('&');
                    if(ampersandPosition != -1) {
                      video_id = video_id.substring(0, ampersandPosition);
                    }
                    embedUrl = '//www.youtube.com/embed/' + video_id;
}
```
This piece of code did fix the embedding issue for me but after I submit the from the iframe tag is empty. The video still embeds successfully in the wysihtml5 editor. 

Any help would be appreciated.

**Comment by arvigeus** [comment]
Will look into it. Meanwhile, I find summernote a better alternative:
http://summernote.org/

**Comment by SanthoshVasabhaktula** [comment]
I have updated the parsing logic to 

```javascript
	if (/^(https?\:\/\/(www\.)?(m\.)?youtube.com\/)/i.test(linkUrl) || /^(https?\:\/\/(www\.)?youtu.be\/)/i.test(linkUrl)) {
		var regExp = /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#\&\?]*).*/;
		var match = linkUrl.match(regExp);
		if ( match && match[7].length == 11 ){
			embedUrl = match[7];
			embedUrl = '//www.youtube.com/embed/' + embedUrl;
		}
	} else if(/^(https?\:\/\/(www\.)?(player\.)?vimeo.com\/)/i.test(linkUrl)) {
		embedUrl = '//player.vimeo.com/video/' + linkUrl.split("/").pop() + "?title=0&byline=0&portrait=0&badge=0";
	} else if(/^(https?\:\/\/(www\.)?dailymotion.com\/)/i.test(linkUrl)) {
		embedUrl = linkUrl.replace("/video/", "/embed/video/");
	} else if(/^(https?\:\/\/(www\.)?vbox7.com\/play:)/i.test(linkUrl)) {
		embedUrl = linkUrl.replace("/play:", "/emb/external.php?vid=");
	} else if(/^(https?\:\/\/(www\.)?metacafe.com\/w(atch)?)/i.test(linkUrl)) {
		embedUrl = linkUrl.replace(/\/w(atch)?\//, "embed");
	}
```
and the change works for the following youtube url's.

>http://www.youtube.com/watch?v=0zM3nApSvMg&feature=feedrec_grec_index
>http://www.youtube.com/user/IngridMichaelsonVEVO#p/a/u/1/QdK8U-VIH_o
>http://www.youtube.com/v/0zM3nApSvMg?fs=1&amp;hl=en_US&amp;rel=0
>http://www.youtube.com/watch?v=0zM3nApSvMg#t=0m10s
>http://www.youtube.com/embed/0zM3nApSvMg?rel=0
>http://www.youtube.com/watch?v=0zM3nApSvMg
>http://youtu.be/0zM3nApSvMg

I agree that summernote is a better alternative - as I am using two different editors for code(markdown) and html(bootstrap3-wysihtml5), where as with summernote we can have one editor for all purposes.

**Comment by arvigeus** [comment]
@SanthoshVasabhaktula thanks for the fix! I merged it, it should work like a charm!

@mrudult I tested it with the fixed version and it appears to work. If not, please open another issue.
