### ISSUE TITLE
Add completely new button

### ISSUE THREAD

**Issue by zimmicz** [arvigeus/bootstrap3-wysihtml5#3]
Is it possible to define a new button with custom template and add it to the toolbar? If so, how?

**Comment by arvigeus** [comment]
Take a look here: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/wiki/Custom-Templates
For example of event handler see /src/bootstrap3-wysihtml5.js, function createToolbar and any of functions starting with init (initTable, initVideo).
Also try http://summernote.org/ - it's far more advanced and easier to extend

**Comment by zimmicz** [comment]
Hi,
I'm a bit confused as I've found a bunch of bootstrap-wysiwyg so far here on GitHub. What is the actual relationship between your repo and the one you linked to? The syntax is a little different.

**Comment by arvigeus** [comment]
The one I linked is the mainstream project. I forked it to suit it up for my personal needs. Probably you were unlucky to find my repo first. I will retire this project once I'm sure I don't need it anymore, so you might want to place your bet on the original project.
