### ISSUE TITLE
How to enable Image resize handles inside text editor Iframe ?

### ISSUE THREAD

**Issue by senrajmca** [arvigeus/bootstrap3-wysihtml5#4]
Hi , 
I have been trying to enable image resize handles inside text editor. can you please help me out.

**Comment by arvigeus** [comment]
Unfortunately, it is not supported. You can try http://summernote.org/ - it supports that.

**Comment by senrajmca** [comment]
Thanks Arvigeus. I am using summernote only.

On Mon, Feb 23, 2015 at 5:56 PM, arvigeus <notifications@github.com> wrote:

> Unfortunately, it is not supported. You can try http://summernote.org/ -
> it supports that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arvigeus/bootstrap3-wysihtml5/issues/4#issuecomment-75532825>
> .
>



-- 
Thanks & Regards
Senthilraj Kalaimani
9916360705
Bangalore
